[build]
  command = "rm -rf .cache node_modules package-lock.json yaml.lock && pnpm install --frozen-lockfile && pnpm build"
  publish = "public"

[build.environment]
  NPM_FLAGS = "--version"  # Prevents Netlify from installing npm
  NETLIFY_USE_PNPM = "true"
