[build]
  command = "export npm_config_legacy_peer_deps=true npm_config_ignore_scripts=false && rm -rf .cache node_modules && npm install --foreground-scripts && npm rebuild sharp --platform=linux --arch=x64 --foreground-scripts --verbose && npx gatsby build"
  publish = "public"