[build]
  command = "rm -rf .cache node_modules && npm install --legacy-peer-deps --foreground-scripts && npm rebuild sharp --platform=linux --arch=x64 --foreground-scripts --verbose && npx gatsby build"
  publish = "public"